#Configure
name: continuos integration GymCore .NET

on:
  push:
    branches: 
    - develop
    - Franco_CI
  pull_request:
    branches: [develop]
    
jobs:
  config_db:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
        
    - name: Set up MySQL 8.0
      uses: mirromutth/mysql-action@master
      with:
        host port: 5859
        container port: 5859
        mysql version: '8.0'
        mysql root password: ${{ secrets.DB_PASSWORD }}
    
    - name: Start MySQL
      run: sudo service mysql start
      
    #- name: Configure MySQL user
    #  run: mysql --execute="use mysql;" --execute= "update user set password=PASSWORD('260999fnb') where User='root';" --execute="flush privileges;" --execute="quit;"
      
    #- name: Restart MySQL
    #  run: sudo service mysql stop | sudo service mysql start
      
    - name: Setup MySQL
      run: mysql --user=root --password=root --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY ${{ secrets.DB_PASSWORD }};" #${{ secrets.DB_PASSWORD }} #--execute="source GymCoreDB.sql"
        
  ci_to_devolp:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
 
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Restore Packages
      run: nuget restore GymCore.sln

    - name: Build solution
      run: msbuild GymCore.sln -t:rebuild -property:Configuration=Release
    
    - name: Run Data Access Layer Test
      run: vstest.console.exe .\DataAccessLayerTest\bin\Release\DataAccessLayerTest.dll
      
    - name: Run Bussines Layer Tests
      run: vstest.console.exe .\BusinessLayerTest\bin\Release\BusinessLayerTest.dll
