#Configure
name: continuos integration GymCore .NET

on:
  push:
    branches: 
    - develop
    - Franco_CI
  pull_request:
    branches: [develop]
    
jobs:     
  buil_and_test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MySQL
    - uses: mirromutth/mysql-action@v1.1
      with:
        host port: 5859
        container port: 5859
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql version: '8.0'
        mysql root password: ${{ secrets.DB_PASSWORD }}
 
    - name: Setup MySQL User
      run: mysql --user=root --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '260999fnb';";
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Restore Packages
      run: nuget restore GymCore.sln

    - name: Build solution
      run: msbuild GymCore.sln -t:rebuild -property:Configuration=Release
    
    - name: Run Data Access Layer Test
      run: vstest.console.exe .\DataAccessLayerTest\bin\Release\DataAccessLayerTest.dll
      
    - name: Run Bussines Layer Tests
      run: vstest.console.exe .\BusinessLayerTest\bin\Release\BusinessLayerTest.dll
