#Configure
name: continuos integration GymCore .NET

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    
jobs:
  ci_to_devolp:
    runs-on: windows-latest
    
    services:
      mysql-service:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: GymCore
        ports:
          - 5859:5859
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
    - uses: actions/checkout@v2
 
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
      
    - name: Setup Laravel
      run: |
        cp .env.ci .env
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        php artisan key:generate
        chmod -R 777 storage bootstrap/cache

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Restore Packages
      run: nuget restore GymCore.sln

    - name: Build solution
      run: msbuild GymCore.sln -t:rebuild -property:Configuration=Release
    
    - name: Run Bussines Layer Tests
      run: vstest.console.exe .\BusinessLayerTest\bin\Release\BusinessLayerTest.dll
      
    - name: Run Data Access Layer Test
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: GymCore
        DB_PORT: 5859
        DB_USER: root
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        php artisan migrate
        vstest.console.exe .\DataAccessLayer\bin\Release\DataAccessLayer.dll
