#Configure
name: continuos integration GymCore .NET

on:
  push:
    branches:
    - develop
    - Franco_CI
  pull_request:
    branches: [develop]
    
jobs:
  config_db:
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        node-version: ['10.x']
        
    steps:
    - uses: actions/checkout@v1
    
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Set up MySQL 8.0
      uses: mirromutth/mysql-action@master
      with:
        mysql version: 8.0
        host port: 5859
        mysql database: GymCore
        mysql root password: ${{ secrets.DB_PASSWORD }}
        
    - name: npm install, build, and test
      run: |
        npm install
        npm run lint
        npm test -- --password=${{ secrets.DB_PASSWORD }}
      env:
        CI: true
        
  ci_to_devolp:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
 
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Restore Packages
      run: nuget restore GymCore.sln

    - name: Build solution
      run: msbuild GymCore.sln -t:rebuild -property:Configuration=Release
    
    - name: Run Bussines Layer Tests
      run: vstest.console.exe .\BusinessLayerTest\bin\Release\BusinessLayerTest.dll
      
    - name: Run Data Access Layer Test
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: GymCore
        DB_PORT: 5859
        DB_USER: root
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        php artisan migrate
        vstest.console.exe .\DataAccessLayer\bin\Release\DataAccessLayer.dll
