#Configure
name: continuos integration GymCore .NET

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    
jobs:
  ci_to_devolp:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup Unit Testing
      uses: actions/checkout@v2.1.0
      
    - name: Restore Packages
      run: nuget restore GymCore.sln

    - name: Build solution
      run: msbuild GymCore.sln -t:rebuild -property:Configuration=Release
    
    - name: Unit Testing
      run: dotnet test
      
      
      
      
      
      
      
    
